# Generated by Django 6.0.3 on 2026-04-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolar_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='curso',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Curso'),
        ),
    ]
