# Generated by Django 6.0.3 on 2026-05-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolar_api', '0003_alter_anotacion_id_alter_asistencia_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='reunion',
            name='curso',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nivel',
            field=models.CharField(choices=[('1B', '1° Básico'), ('2B', '2° Básico'), ('3B', '3° Básico'), ('4B', '4° Básico'), ('5B', '5° Básico'), ('6B', '6° Básico'), ('7B', '7° Básico'), ('8B', '8° Básico'), ('1M', '1° Medio'), ('2M', '2° Medio'), ('3M', '3° Medio'), ('4M', '4° Medio')], default='1B', max_length=2, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='seccion',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='Sección'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nivel',
            field=models.CharField(choices=[('1B', '1° Básico'), ('2B', '2° Básico'), ('3B', '3° Básico'), ('4B', '4° Básico'), ('5B', '5° Básico'), ('6B', '6° Básico'), ('7B', '7° Básico'), ('8B', '8° Básico'), ('1M', '1° Medio'), ('2M', '2° Medio'), ('3M', '3° Medio'), ('4M', '4° Medio')], default='1B', max_length=2, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='seccion',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='Sección'),
        ),
        migrations.AddField(
            model_name='reunion',
            name='nivel',
            field=models.CharField(blank=True, choices=[('1B', '1° Básico'), ('2B', '2° Básico'), ('3B', '3° Básico'), ('4B', '4° Básico'), ('5B', '5° Básico'), ('6B', '6° Básico'), ('7B', '7° Básico'), ('8B', '8° Básico'), ('1M', '1° Medio'), ('2M', '2° Medio'), ('3M', '3° Medio'), ('4M', '4° Medio')], max_length=2, null=True, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='reunion',
            name='seccion',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True, verbose_name='Sección'),
        ),
    ]
